project:
  type: website
  resources:
    - "assets/"
  output-dir: docs


website:
  title: "研究室の机"
  search: true
  navbar:
    pinned: true
    search: true
    left:
      - href: blog.qmd
        text: メモあつめ
  site-url: "https://stats1230.github.io/lab-desk"
  page-footer:
    center: "© S. Tatsuno &nbsp;·&nbsp; Built with [Quarto](https://quarto.org) · [GitHub Pages](https://pages.github.com)"
  image: "assets/image/izu.JPG"
  google-analytics: "G-8WFETJ1CSL"
  open-graph: true
  twitter-card:
    creator: "@stats1230"
    card-style: summary_large_image

lang: ja

author:
  name: "達野俊輔 / S. Tatsuno"
  url: "https://s-tatsuno.github.io"


format:
  html:
    theme:
      light: [sandstone, style.scss]
    toc: true
