project:
  type: website
  resources:
    - "assets/"
  output-dir: docs

website:
  title: "研究室の机"
  navbar:
    left:
      - href: page/blog.qmd
        text: メモあつめ
  site-url: "https://stats1230.github.io/lab-desk"

format:
  html:
    theme:
      light: [sandstone, style.scss]
    toc: true

lang: ja