---
title: "シカゴ・スタイルでの引用方法（著者年方式）"
date: "2026-04-24"
date-modified: "2026-04-24"
categories: [writing]
description: "シカゴ・スタイル（トゥラビアン・スタイル）の著者年方式（Author-Date Style）での引用方法のチートシートです。"
---

この記事では、主に社会科学および自然科学、物理学で用いられる引用スタイルである「シカゴ・スタイル」（トゥラビアン・スタイル / Turabian Style）の「著者年方式（Author-Date Style）」での引用方法をまとめます。この記事では英語文献と日本語文献の両方の記法を掲載しています。

ケイト・L・トゥラビアン（Kate L. Turabian）（2012）『シカゴ・スタイル—研究論文執筆マニュアル—』沼口隆・沼口好雄訳、慶応義塾大学出版会（原著は2007）を参考に友人が作成したものを、微修正して記事にしています。掲載の許可をいただき、ありがとうございます。

著者年方式では、資料の引用を示す手法として、参照した箇所の直後にカッコ入り出典（著者、出版年、関連するページ番号）を明示します。論文の最後の参照リストには、注で明示したあらゆる出典および、参照したが引用しなかった文献を含みます。

もう一方の方式である「注記式参考文献目録方式（Notes-Bibliography Style）」については、[シカゴ・スタイルでの引用方法（参考文献目録方式）](/drafts/chicago-nb.qmd) にまとめています。

<br>
<br>

## 英語文献

### 雑誌論文 (Journal Article)

**本文中 (In-text)**

:::{.card .apa-citation-card}
(Author's Last Name Date of Publication, XX–XX)
:::

**参考文献 (Reference List)**

:::{.card .apa-citation-card}
Author's Last Name, First Name. Date of Publication. "Title of Article: Subtitle of Article." *Title of Journal* Volume Number (Additional Date Information): XX–XX.
:::

- **著者名**
  - [本文] ラストネームのみ記載します。
  - [参考文献] ラストネームを先に書き、カンマ（,）を打ちます。ミドルネームはイニシャル（頭文字）のみ記し、ピリオド（.）を打ちます。
- **発行年**
  - 論文に記載されている著作年を表記します。
- **論文のタイトル**（参考文献）
  - 論文のタイトルをダブルクォーテーション（""）で囲みます。ピリオド（.）を忘れずに。
- **雑誌のタイトル**
  - 雑誌名を斜体（*Italic*）にします。主要な単語の頭文字を大文字にします。
- **巻号**
  - 巻数（Volume）の直後にカンマ（,）を打ち、号数（Issue）をno.に続けて表記します。
- **発行月**
  - 雑誌の発行された月を表記します。コロン（:）を忘れずに。
- **引用ページ**（本文）
  - 引用ページの範囲をenダッシュ（–）でつなぎます。
- **掲載ページ**（参考文献）
  - 掲載ページの範囲をenダッシュ（–）でつなぎます。ピリオド（.）を忘れずに。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(Nayar 2005, 213)

**参考文献**

Nayar, Pramod K. 2005. "Marvelous Excesses: English Travel Writing and India, 1680–1727." *Journal of British Studies* 44, no.2 (April): 213–38.
:::


### オンライン上の雑誌論文 (Journal Article Online)

**本文中 (In-text)**

:::{.card .apa-citation-card}
(Author's Last Name Date of Publication)
:::

**参考文献 (Reference List)**

:::{.card .apa-citation-card}
Author's Last Name, First Name. Date of Publication. "Title of Article: Subtitle of Article." *Title of Journal* Volume Number (Additional Date Information): XX–XX. URL (accessed Date of Access).
:::

- **著者名**
  - [本文] ラストネームを記載します。
  - [参考文献] ラストネームを先に書き、カンマ（,）を打ちます。ミドルネームはイニシャル（頭文字）のみ記し、ピリオド（.）を打ちます。
- **発行年**
  - 論文に記載されている著作年を表記します。
- **論文のタイトル**（参考文献）
  - 論文のタイトルをダブルクォーテーション（""）で囲みます。ピリオド（.）を忘れずに。
- **雑誌のタイトル**（参考文献）
  - 雑誌名を斜体（*Italic*）にします。主要な単語の頭文字を大文字にします。
- **巻号**
  - 巻数（Volume）の直後にカンマ（,）を打ち、号数（Issue）をno.に続けて表記します。
- **発行月**
  - 論文の発行された月を丸括弧（）で囲んで表記します。
- **URL**
  - 記事へのURLを表記します。
- **アクセス日**
  - 当該Webページにアクセスした日を丸括弧（）で囲み「accessed」に続けて表記します。コロン（:）を忘れずに。
- **引用ページ**（本文）
  - 引用ページの範囲をenダッシュ（–）でつなぎます。
- **掲載ページ**（参考文献）
  - 掲載ページの範囲をenダッシュ（–）でつなぎます。ピリオド（.）を忘れずに。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(Shapiro 2000, 642)

**参考文献**

Shapiro, Lawrence A. 2000. "Multiple Realizations." *Journal of Philosophy* 97, no.12 (December): 635–54. http://links.jstor.org/sici?sici=0022-362X%2820012%2997%3A12%3C635%3AMR%3E2.0.CO%3B2-Q (accessed June 27, 2006)
:::


### 本 (Book)

**本文中 (In-text)**

:::{.card .apa-citation-card}
(Author's Last Name Date of Publication, XX–XX)
:::

**参考文献 (Reference List)**

:::{.card .apa-citation-card}
Author's Last Name, First Name. Date of Publication. *Title of Book: Subtitle of Book*. Edition Number ed. Publisher's Name.
:::

- **著者名**
  - [本文] ラストネームのみ記載します。複数人いる場合はカンマ（,）でつなぎ、最後の著者の前にandを書きます。4人以上の場合、筆頭著者の名前のみを記し、et al.を書くことにより省略をします。
  - [参考文献] ラストネームを先に書き、カンマ（,）を打ちます。ミドルネームはイニシャル（頭文字）のみ記し、ピリオド（.）を打ちます。複数人いる場合はカンマ（,）でつなぎ、最後の著者の前にandを書きます。
- **発行年**
  - 本に記載されている著作年を表記します。
- **本のタイトル**（参考文献）
  - 本のタイトルを斜体（*Italic*）にします。ピリオド（.）を忘れずに。主要な単語の頭文字を大文字にします。
- **版**（参考文献）
  - 版の番号を記し、続けて「ed.」を表記します。
- **出版社**
  - 出版社の名前を書きます。出版地は不要です。複数の出版社から出版されている場合、セミコロン（;）を用いてつなぎます。
- **引用ページ**
  - 引用ページの範囲をenダッシュ（–）でつなぎます。ピリオド（.）を忘れずに。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(Daniels 2002, 84)

**参考文献**

Daniels, Roger. 2002. *Coming to America: A History of Immigration and Ethnicity in American Life*. 2nd ed. Harper Perennial.
:::


### 編集本 (Edited Book)

**本文中 (In-text)**

:::{.card .apa-citation-card}
(Editor's Last Name Date of Publication, XX–XX)
:::

**参考文献 (Reference List)**

:::{.card .apa-citation-card}
Editor's Last Name, First Name, ed. Date of Publication. *Title of Book: Subtitle of Book*. Publisher's Name.
:::

- **編者名**
  - [本文] ラストネームを記載します。編者であることを示すため、名前の後に「ed.」を付けます。
  - [参考文献] ラストネームを先に書き、カンマ（,）を打ちます。ミドルネームはイニシャル（頭文字）のみ記し、ピリオド（.）を打ちます。編者であることを示すため、名前の後にed.を付けます。
- **発行年**
  - 本に記載されている著作年を表記します。
- **本のタイトル**（参考文献）
  - 本のタイトルを斜体（*Italic*）にします。ピリオド（.）を忘れずに。主要な単語の頭文字を大文字にします。
- **出版社**
  - 出版社の名前を書きます。出版地は不要です。複数の出版社から出版されている場合、セミコロン（;）を用いてつなぎます。
- **引用ページ**（本文）
  - 引用ページの範囲をenダッシュ（–）でつなぎます。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(Noll 1989, 75–80)

**参考文献**

Noll, Mark A., ed. 1989. *Religion and American Politics: From the Colonial Period to the 1980s*. Oxford University Press.
:::


### 編集本の特定の章 (Single Chapter in an Edited Book)

**本文中 (In-text)**

:::{.card .apa-citation-card}
(Chapter Author's Last Name Date of Publication, XX–XX)
:::

**参考文献 (Reference List)**

:::{.card .apa-citation-card}
Chapter Author's Last Name, First Name. Date of Publication. "Title of Chapter: Subtitle of Chapter." In *Title of Book: Subtitle of Book*, ed. Editor's First and Last Names, XX–XX. Publisher's Name.
:::

- **論文の筆者名**
  - [本文] ラストネームを表記します。
  - [参考文献] ラストネームを先に書き、カンマ（,）を打ちます。ミドルネームはイニシャル（頭文字）のみ記し、ピリオド（.）を打ちます。
- **発行年**
  - 本に記載されている著作年を表記します。
- **章のタイトル**（参考文献）
  - 論文のタイトルを表記します。ピリオド（.）を忘れずに。
- **本のタイトル**（参考文献）
  - 本のタイトルの前に「In」と記載し、本の一部であることを示します。本のタイトルを斜体（*Italic*）にします。ピリオド（.）を忘れずに。主要な単語の頭文字を大文字にします。
- **編者名**（参考文献）
  - 「ed.」（複数人である場合には「eds.」）に続けて、編者のファーストネームを先に書き、ラストネームを続けます。
- **引用ページ**（本文）
  - 引用ページの範囲をenダッシュ（–）でつなぎます。
- **掲載ページ**（参考文献）
  - 掲載ページの範囲をenダッシュ（–）でつなぎます。ピリオド（.）を忘れずに。
- **出版社**
  - 出版社の名前を書きます。出版地は不要です。ピリオド（.）を忘れずに。複数の出版社から出版されている場合、セミコロン（;）を用いてつなぎます。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(Spirn 1996, 101)

**参考文献**

Spirn, Anne Whiston. 1996. "Constructing Nature: The Legacy of Frederick Law Olmsted." In *Uncommon Ground: Rethinking the Human Place in Nature,* ed. William Cronon, 91–113. W.W.Norton and Company.
:::


### 新聞記事（通常、参考文献目録に入れる必要なし）

**本文中 (In-text)**

:::{.card .apa-citation-card}
(*Publisher's Name* Year of Publication)
:::

**参考文献 (Reference List)**

:::{.card .apa-citation-card}
*Publisher's Name*, Edition Number, Year of Publication. Heading. Date of Publication.
:::

- **新聞社**
  - 新聞社の名前を斜体（*Italic*）にします。
- **版番号**
  - 版によって記載項目が変化または削除される可能性があるため、記載します。必ずしも数字ではなく、「最終版（final edition）」や「南西部版（Midwest edition）」といった場合もあります。
- **刊行年**
  - 新聞に記載されている刊行年を記載します。
- **記事の見出し**
  - 記事の見出しを記載します。
- **日付**
  - 新聞に記載されている日付を記載します。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(*New York Times* 2004)

**参考文献**

*New York Times*, national edition. 2004. Obituary of Jacques Derrida. October 10.
:::


### 手稿

**本文中 (In-text)**

:::{.card .apa-citation-card}
(Title of Manuscript, Date of Publication, Types of Manuscript)
:::

**参考文献（議論に不可欠または頻繁に引用した場合のみ）**

:::{.card .apa-citation-card}
Title of Manuscript. Types of Manuscript. Location of Manuscript.
:::

- **資料のタイトル**
  - 資料のタイトルを記載します。資料に表題があるが著者名がない、または表題が著者名よりも重要な場合は、表題を最初に記載します。
- **資料の日付**
  - 資料の作成された年月日を記載します。
- **資料の種類**
  - 資料の種類（文書、手稿等）を記載します。
- **所蔵場所**
  - 当該コレクションが所蔵されている場所を記載します。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(James Oglethorpe to the trustees, January 13, 1733, Egmont Manuscripts)

**参考文献**

Pennsylvania Society for the Abolition of Slavery. Papers. Historical Society of Pennsylvania.
:::


<br>
<br>

## 日本語文献

### 雑誌論文

**本文中**

:::{.card .apa-citation-card}
(著者名 発行年、XX–XX)
:::

**参考文献**

:::{.card .apa-citation-card}
著者名、発行年「論文のタイトル—副題—」『雑誌のタイトル』巻号（発行月）XX–XX. DOI
:::

- **著者名**
  - [本文] 著者の姓のみ記載します。著者が複数名いる場合は、著者間を「・」（なかぐろ）でつなぎます。
  - [参考文献] 著者を姓・名の順で表記します。著者が複数名いる場合は、著者間を「・」（なかぐろ）でつなぎます。
- **発行年**
  - 論文に記載されている著作年を表記します。
- **論文のタイトル**（参考文献）
  - 論文のタイトルを「 」（一重かぎ括弧）で囲みます。副題（サブタイトル）がある場合は「－」（ダッシュ）でタイトルとつなぎます。
- **雑誌のタイトル**
  - 掲載雑誌のタイトルを『 』（二重かぎ括弧）で囲みます。
- **巻号**
  - 掲載雑誌の巻数を表記します。
- **発行月**
  - 雑誌の発行された月を表記します。
- **引用ページ**（本文）
  - 引用ページの範囲をenダッシュ（–）でつなぎます。
- **掲載ページ**（参考文献）
  - 掲載ページの範囲をenダッシュ（–）でつなぎます。ピリオド（.）を忘れずに。
- **DOI**
  - 論文にDOI（Digital Object Identifier）が付与されている場合は、リンク形式で記載します。URLの表示が変わる可能性があるため、末尾に句点（.）は付けません。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(秋山 2023, 60)

(市原 2021, 42–47)

(大林 2013, 139–152)

(山田 2002, 414–429)

**参考文献**

秋山信将、2023「グローバル・ヘルスレジームにおける調査・検証権限の制度的考察－不拡散レジームとの比較において（ヘルスをめぐる国際政治）－」『国際政治』211号 58–73.

市原麻衣子、2021「変容する『人権・民主主義外交』－民主主義国の国際連携と日本のあり方－」『外交』67号 42–47.

大林一広、2013「反乱軍の組織と内戦後の和平期間」『国際政治』174号 139–152. https://doi.org/10.11375/kokusaiseiji.174_139

山田敦、2002「国際関係を学ぶ人へ」『一橋論叢』127巻4号 414–429. https://doi.org/10.15057/10298
:::


### 本

**本文中**

:::{.card .apa-citation-card}
(著者名 発行年、XX–XX)
:::

**参考文献**

:::{.card .apa-citation-card}
著者名（発行年）『本のタイトル—副題—』版情報、出版社
:::

- **著者名**
  - [本文] 著者の姓を表記します。著者が複数名いる場合は「・」（なかぐろ）でつなぎます。4人以上の場合、筆頭著者の名前のみを記し、「他」を書くことにより省略をします。
  - [参考文献] 著者を姓・名の順で表記します。著者が複数名いる場合は「・」（なかぐろ）でつなぎます。
- **発行年**
  - 本に記載されている著作年を表記します（基本的には参照した版の第一刷の年）。
- **本のタイトル**（参考文献）
  - 本のタイトルを『 』（二重かぎ括弧）で囲みます。
- **版情報**（参考文献）
  - 本のタイトルのあとに「第X版」という形式で表記します。
- **出版社**
  - 出版社の名前を書きます。出版地は不要です。
- **引用ページ**
  - 引用ページの範囲をenダッシュ（–）でつなぎます。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(高坂 2017、30–31)

(佐渡島・吉野 2021、10–11)

(松林 2021、20–21)

**参考文献**

高坂正尭（2017）『国際政治－恐怖と希望－』改版、中央公論社

佐渡島紗織・吉野亜矢子（2021）『これから研究を書くひとのためのガイドブック―ライティングの挑戦15週間―』第2版、ひつじ書房

松林哲也（2021）『政治学と因果推論－比較から見える政治と社会－』岩波書店
:::


### 編集本

**本文中**

:::{.card .apa-citation-card}
(編者名 発行年、XX–XX)
:::

**参考文献**

:::{.card .apa-citation-card}
編者名（発行年）『本のタイトル—副題—』版、出版社
:::

- **編者名**
  - [本文] 編者の姓を表記します。編者であることを示すため、名前の後に「編」を付けます。編者が複数名いる場合は「・」（なかぐろ）でつなぎます。4人以上の場合、筆頭編者の名前のみを記し、「他」を書くことにより省略をします。
  - [参考文献] 編者を姓・名の順で表記します。編者であることを示すため、名前の後に「編」を付けます。編者が複数名いる場合は「・」（なかぐろ）でつなぎます。
- **発行年**
  - 本に記載されている著作年を表記します。
- **本のタイトル**（参考文献）
  - 本のタイトルを『 』（二重かぎ括弧）で囲みます。
- **版情報**（参考文献）
  - 本のタイトルのあとに「第X版」という形式で表記します。
- **出版社**
  - 出版社の名前を書きます。出版地は不要です。
- **引用ページ**（本文）
  - 引用ページの範囲をenダッシュ（–）でつなぎます。


### 編集本の特定の章

**本文中**

:::{.card .apa-citation-card}
(著者名 発行年、XX–XX)
:::

**参考文献**

:::{.card .apa-citation-card}
著者名（発行年）「論文のタイトル—副題—」『本のタイトル—副題—』編者名、XX–XX、出版社
:::

- **論文情報**
  - 通常の論文と同様の要領で、章の情報を表記します。
- **発行年**
  - 本に記載されている著作年を表記します。
- **章のタイトル**（参考文献）
  - 論文のタイトルを表記します。ピリオド（.）を忘れずに。
- **本のタイトル**（参考文献）
  - 本のタイトルを二重かぎ括弧でくくり、副題がある場合は「－」（ダッシュ）で囲みます。
- **編者名**（参考文献）
  - 編者の名前を表記します。編者であることを示すため、「編」「編著」を名前の後に表記します。
- **引用ページ**（本文）
  - 引用ページの範囲をenダッシュ（–）でつなぎます。
- **掲載ページ**（参考文献）
  - 掲載ページの範囲をenダッシュ（–）でつなぎます。
- **出版社**（参考文献）
  - 出版社の名前を書きます。出版地は不要です。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(中山・土井 2021、220)

(宮城 2017、350–52)

**参考文献**

中山祐美・土井翔平（2021）「国際難民制度のテキスト分析－UNHCRにおける北欧諸国の発言を事例に－」『国際関係研究の方法－解説と実践－』鈴木基史・飯田啓輔編、213–236、東京大学出版会

宮城大蔵（2017）「1960年代における日本の援助とアジア国際秩序―戦後処理と冷戦の影―」『冷戦変容期の国際開発援助とアジア』渡辺昭一編著、340–367、ミネルヴァ書房
:::


### 新聞記事（通常、参考文献目録に入れる必要なし）

**本文中**

:::{.card .apa-citation-card}
(新聞社 刊行年)
:::

**参考文献**

:::{.card .apa-citation-card}
新聞社（刊行年月日）「記事のタイトル」版情報
:::

- **新聞社**
  - 新聞社の名前を表記します。
- **刊行年**
  - 新聞に記載されている刊行年を記載します。
- **日付**
  - 新聞に記載されている日付を記載します。
- **記事の見出し**
  - 記事のタイトルを「 」（一重かぎ括弧）でくくります。タイトル内のかぎ括弧は二重にします。副題がある場合は「－」（ダッシュ）で囲みます。
- **版番号**
  - 版によって記載項目が変化または削除される可能性があるため、記載します。

:::{.callout-note collapse="true" title="参考文献表記例" .citation-card}
**本文**

(朝日新聞デジタル 2024)

**参考文献**

朝日新聞デジタル（2024年3月8日）「『人口の半分が人道危機』泥沼化するスーダン―国際社会の傍観と謀略―」https://www.asahi.com/articles/ASS38659RS2SUHBI00B.html
:::
