---
title: "卒論・修論の体裁 Tips"
permalink: /research-tips.html
toc_label: "目次"
---

卒業論文・修士論文を執筆する際に役に立つかもしれない情報を雑多にまとめます。

### 基本的なガイドライン
※私が所属する研究室で、少なくとも2025年に指示された内容です。他のゼミに所属している方や新しい指示がある場合は、当然そちらに従ってください。

- 表紙のあとに、内表紙をいれる。
- 目次を入れる。
  - 修士論文では、図表の目次も入れる。
- 要約を入れる。
- 本文の文字の大きさは、10.5ポイント、脚注は、10ポイント
  - 英語の場合は、本文11ポイント、脚注10ポイント
- 各章のタイトルは、研究方法、主張などが分かりやすいタイトルにする。
  - 章のタイトルに、副題を付けるのも一案。
  - また、各章の初めは、改頁する。
- 図表でカラーを使っている場合は、それでもよい。
  - 但し、白黒で印刷・コピーする人がいる可能性を考え、線の種類や背景の模様を変えて、白黒でもわかりやすいようにする。
- 参考文献リストや脚注の記載を再度確認する。
- 謝辞は結論ではなく「あとがき」に書く。

### その他、役に立つ情報
- 一橋大学商学部、松井剛ゼミナール「[卒業論文の体裁に関するメモ](https://researchmap.jp/multidatabases/multidatabase_contents/detail/243998/7734311aa222dd013102a08a8e638575?frame_id=541475)」
- 一橋大学社会学研究科「[修士論文表紙作成要領](https://www.soc.hit-u.ac.jp/info/student/cover_m.html)」

### 引用スタイル
- 日本語の場合、APA準拠とするか、学会の引用スタイルに従うのがよい。
  - たとえば、[日本国際政治学会の投稿規定](https://jair.or.jp/membership/application/rules_for_papers.html)

### 個人的な Tips
- [伝わるデザイン](https://tsutawarudesign.com/)
  - プレゼン含め、伝えやすいデザインの方法を解説しているサイト。フォントの話から配色の話、バリアフリーについても触れられており、報告資料の作成の際に必携。
  - より一般的なデザインの話は、[書籍「伝わるデザインの基本」](https://gihyo.jp/book/2021/978-4-297-11985-0)に掲載されている。
- 図表のタイトルは、図は下、表は上。
- 図表はページの上部に来るように調整する。

### 製本と表紙の雛形
卒業論文及び修士論文は、ハードカバーを付した製本を施して提出することが求められます。

通常製本は、大学の生協または大学周辺の文具店に注文します。下記をご確認ください。各ページには、表紙の雛形もおいてあります。

- 一橋大学生協「[卒業論文製本](https://www.univcoop.jp/hit-u/info/info_115.html)」
- 文具しまだ「[論文製本](https://www.bungu-shimada.com/ronbun.html)」
